[package]
version = "0.1.0"
name = "wormhole-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "4.0.0"
fibonacci-lib = { path = "../lib" }
sha2 = "0.10"
serde = "1.0.219"
